### ISSUE TITLE
Deployment error on docker..

### ISSUE THREAD

**Issue by platini76** [lmagyar/homeassistant-addon-portainer#29]
my config.:

version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - TZ=Europe/Rome
    volumes:
      - ./volumes/homebridge:/homebridge

error:

Deployment error
failed to deploy a stack: Container homebridge-homebridge-1 Creating Container homebridge-homebridge-1 Created Container homebridge-homebridge-1 Starting Error response from daemon: error while creating mount source path '/data/compose/14/volumes/homebridge': mkdir /data: read-only file system

please can someone has suggestions?

**Comment by lmagyar** [comment]
How is this issue related to this add-on? This is not this add-on's config.
Note: This add-on is not to install general containers on a Home Assistant docker.
