### ISSUE TITLE
how to upgrade to business edition...

### ISSUE THREAD

**Issue by platini76** [lmagyar/homeassistant-addon-portainer#30]
i have a code but system say error...
any suggestion?

**Comment by platini76** [comment]
failed to deploy upgrade stack: Network portainer-upgrade-1689353906-2-18-4_default Creating Network portainer-upgrade-1689353906-2-18-4_default Created Container portainer-upgrade-1689353906-2-18-4-updater-1 Creating Container portainer-upgrade-1689353906-2-18-4-updater-1 Created portainer-upgrade-1689353906-2-18-4-updater-1 | {"level":"info","image":"portainer/portainer-ee:2.18.4","time":1689353908,"caller":"/home/runner/work/portainer-updater/portainer-updater/portainer/portainer.go:76","message":"Updating Portainer on standalone environment"} portainer-upgrade-1689353906-2-18-4-updater-1 | {"level":"info","containerId":"09603e5f79d38ab2ef21a7f329e96e1497b4fec69cddcd66171f103e42ee4e9d","image":"portainer/portainer-ee:2.18.4","time":1689353908,"caller":"/home/runner/work/portainer-updater/portainer-updater/dockerstandalone/update.go:28","message":"Starting update process"} Aborting on container exit... Container portainer-upgrade-1689353906-2-18-4-updater-1 Stopping Container portainer-upgrade-1689353906-2-18-4-updater-1-update Stopping Container portainer-upgrade-1689353906-2-18-4-updater-1-update Stopped Container portainer-upgrade-1689353906-2-18-4-updater-1 Stopped


and after: 
upgrade failed: server should have been restarted by the updater

**Comment by lmagyar** [comment]
You can't update. Add-ons' code are not modifiable by the users, only by the add-on's developer. They are not general docker containers. Please read more about add-ons in HA documentation.
